"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/home/navbar/Navbar";
import Footer from "@/components/home/footer/Footer";

import { Toaster } from "react-hot-toast";


import { Providers } from "./providers";  // 👈 we'll create this
import { usePathname } from "next/navigation";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "quick drop",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
   const pathname = usePathname();
  const hideOnRoutes = ["/dashboard"];
  const shouldHide = pathname.startsWith("/dashboard");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>




         

          {
            !shouldHide && <Navbar />
          }
          
          {children}
          {
            !shouldHide &&  <Footer />
          }
           <Toaster></Toaster>

        </Providers>
      </body>
    </html>
  );
}
